export const PostsActionTypes = {
	FETCH_POSTS_START: 'FETCH_POSTS_START',
	FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
	FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
	UPDATE_POST_VOTES: 'UPDATE_POST_VOTES'
};
