export const SubredditActionTypes = {
	SET_CURRENT_SUBREDDIT: 'SET_CURRENT_SUBREDDIT',
	FETCH_SUBREDDIT_START: 'FETCH_SUBREDDIT_START',
	FETCH_SUBREDDIT_SUCCESS: 'FETCH_SUBREDDIT_SUCCESS',
	FETCH_SUBREDDIT_FAILURE: 'FETCH_SUBREDDIT_FAILURE'
};
